## Concatenation and Addition of index in list

In [5]:
list1=[1,2,3,4]
list2=[5,6,7,8]

print("Concatenation result: ",list1+list2)

sum_l=[]
for num1,num2, in zip(list1,list2):
  sum_l.append(num1+num2)
print("Addition of index result: ",sum_l)

Concatenation result:  [1, 2, 3, 4, 5, 6, 7, 8]
Addition of index result:  [6, 8, 10, 12]


## **Numpy**

In [7]:
import numpy as np

In [9]:
arr1=np.array(list1)
arr1
arr2=np.array(list2)
arr2
sum_l2=arr1+arr2
sum_l2

array([ 6,  8, 10, 12])

In [11]:
type(arr1)

numpy.ndarray

In [13]:
arr1.ndim

1

In [16]:
list3=[[1,2,3],[4,5,6]]
arr3=np.array(list3)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3.ndim

2

In [21]:
arr3.shape

(2, 3)

In [24]:
arr4=np.arange(6)
arr4

array([0, 1, 2, 3, 4, 5])

In [26]:
arr5=arr4.reshape(2,3)
arr5

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
arr4.sum()

15

In [30]:
arr4.mean()

2.5

In [32]:
np.median(arr4)

2.5

In [34]:
np.sqrt(arr5)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.random.rand(3,4)

array([[0.37985253, 0.535001  , 0.28287221, 0.81837426],
       [0.0953255 , 0.99509044, 0.39086948, 0.39999848],
       [0.6117649 , 0.79325559, 0.10393029, 0.2858203 ]])

Pandas

In [39]:
import pandas as pd

In [40]:
data=pd.read_csv('/content/auto-mpg.csv')

In [41]:
data

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]